### ISSUE TITLE
Payments

### ISSUE THREAD

**Issue by hfelashry** [wohahobg/pterosync#1]
Hey! I came across this and i have 2 questions, does this have normal subscription payment? and what payment gateways does pterosync support?

**Comment by FurJorden** [comment]
Hey, Pterosync supports any Payment Gateways because the payment is managed by WHMCS and not by a Module like PteroSync. You need to set up any Payment Gateway on WHMCS what you like to accept.

**Comment by FurJorden** [comment]
> Hey, Pterosync supports any Payment Gateways because the payment is managed by WHMCS and not by a Module like PteroSync. You need to set up any Payment Gateway on WHMCS what you like to accept.

**Comment by FurJorden** [comment]
> Hey! I came across this and i have 2 questions, does this have normal subscription payment? and what payment gateways does pterosync support?

Hey, Pterosync supports any Payment Gateways because the payment is managed by WHMCS and not by a Module like PteroSync. You need to set up any Payment Gateway on WHMCS what you like to accept.
