### ISSUE TITLE
Multiple Ports

### ISSUE THREAD

**Issue by spudgun1001** [wohahobg/pterosync#13]
It seems that multiple ports aren't being opened. Here is my config.

I need a main server port, server port+400 and an RCON port (between 8188-8900). However it just seems to make a server port and only assign the server port. Any ideas on if my config is wrong or if there is an underlying issue?

![image](https://github.com/wohahobg/PteroSync/assets/48835529/cb01d135-4fc7-4f7f-aa02-1a73111950c8)

![image](https://github.com/wohahobg/PteroSync/assets/48835529/7367d887-b50c-4bf3-be7b-97370b6b3590)

**Comment by spudgun1001** [comment]
I have figured out the issue.

The module doesn't automatically create the ports, you have to do it manually.

**Comment by spudgun1001** [comment]
I have also noticed that RCON_PORT does not automatically assign to variables on your server. I have an egg which has the Environment Variable RCON_PORT.

**Comment by wohahobg** [comment]
> I have also noticed that RCON_PORT does not automatically assign to variables on your server. I have an egg which has the Environment Variable RCON_PORT.

That's very wired it should.

Can you please try with the lasted main branch as I have done a lot of changes there.

**Comment by spudgun1001** [comment]
I just tested the latest branch, no luck. It does assign all required ports, just doesn't automatically assign any value part from Server Port.

![image](https://github.com/wohahobg/PteroSync/assets/48835529/969a28c1-a07f-4e21-bf34-40bf52a01df2)

![image](https://github.com/wohahobg/PteroSync/assets/48835529/dd8ea4be-5bda-4866-882f-78827bbe2856)

**Comment by wohahobg** [comment]
Hi,

Can you please share with me the module log ?
Screenshots please.

**Comment by spudgun1001** [comment]
![image](https://github.com/wohahobg/PteroSync/assets/48835529/ec8943d9-b4bf-4100-bd02-d6c27a6904c4)

![image](https://github.com/wohahobg/PteroSync/assets/48835529/8176348c-2f4d-4e2b-ae10-324f977a220d)

![image](https://github.com/wohahobg/PteroSync/assets/48835529/874d2a80-69e1-40cc-b655-30c603ff5677)


Module isn't assigning the variable "RCON_PORT" but it does seem to recognise it on the creation

**Comment by wohahobg** [comment]
can u please share with me this error 
![image](https://github.com/wohahobg/PteroSync/assets/21145247/7fb205e8-8f63-4397-95f3-a5d97fa8cd1a)

**Comment by spudgun1001** [comment]
Array
(
    [errors] => Array
        (
            [0] => Array
                (
                    [code] => ValidationException
                    [status] => 422
                    [detail] => The Query Port variable may not be greater than 20.
                    [meta] => Array
                        (
                            [source_field] => environment.QUERY_PORT
                            [rule] => max
                        )

                )

        )

    [status_code] => 422
)

**Comment by wohahobg** [comment]
Here we go.

Pterodactyl does not like something about QUERY_PORT.

Can you please share with me your product setup, like full screen.

**Comment by spudgun1001** [comment]
![image](https://github.com/wohahobg/PteroSync/assets/48835529/9dc54d9c-5c86-4d0b-b983-adac44526d37)

**Comment by spudgun1001** [comment]
I have resolved this. So my query variable had a max value of "20" so it wasn't setting the variables

**Comment by wohahobg** [comment]
![image](https://github.com/wohahobg/PteroSync/assets/21145247/cbae6f88-67a7-4e71-8034-1781e17b5195)


So idk why pterodactyl does not like that. Try with less number or change the ptoradactyl egg rule .

**Comment by wohahobg** [comment]
> I have resolved this. So my query variable had a max value of "20" so it wasn't setting the variables

Nice!

**Comment by spudgun1001** [comment]
Thanks for the help :)
