### ISSUE TITLE
No nodes satisfying the requirements specified for automatic deployment could be found.

### ISSUE THREAD

**Issue by kcorr** [wohahobg/pterosync#15]
What's weird is it was all working just fine with the pterodactyl module, but after switching over to this one it seems to not know where to deploy.. I have added the server, placed API creds, an admin account API creds, all ports are allocated, but it keeps showing me no nodes available.

Any help appreciated, thanks!

**Comment by wohahobg** [comment]
Hi,

Please double check your product settings, as by default this module use GB so if you have input for example 1024 memory in the old module that's MB but for this module this is GB so that will be 1024GB.

Share with me your module log and your product settings.

**Comment by kcorr** [comment]
God bless... You were on the money.. I was trying to to TBs of memory... Thank you for the quick response!
