### ISSUE TITLE
Update documentation - server_ip:server_port as whmcs service domain

### ISSUE THREAD

**Issue by inferno-cc** [wohahobg/pterosync#2]
Hi,

First at all, your modification is great and I'm loving it :)
That could be nice if you could update the documentation and specify that server_ip:server_port is being set as the service domain in the whmcs product that also can be used as an email template variable.

Thanks!

**Comment by wohahobg** [comment]
Hey,

Thanks for the feedback.

I did not know that can be use in this way, I will update the wiki page asap

**Comment by wohahobg** [comment]
Done  - https://github.com/wohahobg/PteroSync/wiki/Email-Templete
