### ISSUE TITLE
Port offset doest not work when using the IP Alias

### ISSUE THREAD

**Issue by p-menta** [wohahobg/pterosync#23]
The log returns "Ports not found" with the port being available while using the alias IP.
![image](https://github.com/user-attachments/assets/1bd66ce8-2db3-48c9-bcaa-7c0ad35c9af2)

The port offset function *does work* fine when *not* using the alias option.

**Comment by wohahobg** [comment]
Hey can you please share with me your product setup. I assume that your product settings are not set in current way.

**Comment by p-menta** [comment]
here is the product>module setting view
![image](https://github.com/user-attachments/assets/f2d66e23-c411-45ce-b708-ae20ea6574a3)

A customer ordered one hour ago and it worked fine again.
![image](https://github.com/user-attachments/assets/7fb33879-4eb9-40de-9165-a617988f2a20)

Now using the setting 
`"use_alias_ip": true`

![image](https://github.com/user-attachments/assets/6c8aa438-2060-405d-b591-48b187ef1bf5)

**Comment by p-menta** [comment]
in the last image, the server was created on the port 16342.
The request shows the port 16343 available.
https://pastebin.com/wUSAd83p#google_vignette
![image](https://github.com/user-attachments/assets/fee24f05-a5b8-443f-aea7-320b54628958)

just a guess, but perhaps the code is searching for [ip] instead of the [alias] [here](https://github.com/wohahobg/pterosync/blob/63231a4e2dda65e83568e182f12978e7ac65aa6d/pterosync/helper.php#L580) ?

maybe [pteroSync_getServerIPAndPort](https://github.com/wohahobg/pterosync/blob/63231a4e2dda65e83568e182f12978e7ac65aa6d/pterosync/helper.php#L822) should be called before server creation.
I will test it and get back with the result.

**Comment by wohahobg** [comment]
The code is searching only for an ip same as pterodactyl.

**Comment by wohahobg** [comment]
How is work is:

It creating 1st the server by pterodactyl then it searching for an extra ports and etc if required on same ip as server ip, and if there is no matches it search for different ip and port until it match them.

**Comment by p-menta** [comment]
I inserted this block of code in order to try to understand better what is happening. The first output is with the alias turned off, and then with the alias turned on.
![image](https://github.com/user-attachments/assets/089ca14a-4f64-4afb-bf39-ae9dc2de694a)

alias = false
https://pastebin.com/YnWqz9YT

alias = true
https://pastebin.com/guLbm4re

**Comment by wohahobg** [comment]
The allies is only used for display use in clinetarea.

The module won't search ip by allies.

**Comment by p-menta** [comment]
Can you please confirm that `$_SERVER_IP` is not being replaced by the alias [here](https://github.com/wohahobg/pterosync/blob/e93e82fc18548d1b688f05afea7ee2fec988954b/pterosync/helper.php#L828) ?

Because I don't understand why, when printing the $_SERVER_IP variable in the log, it shows the Alias IP.
![image](https://github.com/user-attachments/assets/0d96b240-1150-4478-b075-b249909f33f4)

**Comment by wohahobg** [comment]
That replace it yes. But it does it and the end. 

What is your goal ? To use allies ips instand of normal one to create a server?

**Comment by p-menta** [comment]
Your module can create offset ports when `"use_alias_ip": false`
When using `"use_alias_ip": true`, port offset does not work.

The module searches for new ports using the alias IP because the `$_SERVER_IP` is being redefined to the alias at the end.

To achieve the expected result, I edited the `pteroSync_getServerIPAndPort()` function so that it creates a specific variable for the alias when needed.
If the boolean `use_alias_ip` is `true`, then `pteroSync_updateServerDomain()` is called using:
`pteroSync_updateServerDomain(alias, $_SERVER_PORT, $params);`

**Comment by wohahobg** [comment]
Ahh I see where the issue was. I have added new variable that store the alias ip and used only when it need to store the IP in whmc. You can see in the commit 7aa0cd217a570df7abaabe21fc894f0a4c417855. Try to use the main branch.

**Comment by p-menta** [comment]
Using the main branch, the server is created correctly with all ports and the domain is updated correctly with the alias, but in the client area, this error occurs:
![image](https://github.com/user-attachments/assets/a08f0878-2fe5-4f51-ba1c-4fa66a8343f5)

Passing the `$serverAliasIp` argument to the `pteroSyncGenerateServerStatusArray()` function and replacing `$address` with it worked 100% for me. Thank you very much for the module and your work.

**Comment by wohahobg** [comment]
Should be okay now.
