### ISSUE TITLE
Do not send the password

### ISSUE THREAD

**Issue by JockerGamer** [wohahobg/pterosync#28]
Well, I configured the Email to show the user (Client Email) and the password generated by WHMCS, but when it sends the email to the client the {$server_password} variable doesn't work.

Is there a correct variable or something I can do to fix this? I've talked to several people but I still have the same problem.

**Comment by JockerGamer** [comment]
![image](https://github.com/user-attachments/assets/c0d48822-5776-4e91-926d-992c361fab94)

**Comment by wohahobg** [comment]
There is no password vsriable. Unless whmc provided one that the module has no control over it.

**Comment by JockerGamer** [comment]
> There is no password vsriable. Unless whmc provided one that the module has no control over it.

And how should I provide the password for clients to log into the hosting? Since WHMCS creates a password automatically.

**Comment by JockerGamer** [comment]
I would like to send an email containing login information to customers, including the password and username (Email).

**Comment by wohahobg** [comment]
Pterodactyl is sending email when an account is created for password reset.

**Comment by JockerGamer** [comment]
> Pterodactyl is sending email when an account is created for password reset.

It is not 😢

**Comment by JockerGamer** [comment]
Is there a more direct means of contact, like Discord, to send you images about it?

**Comment by wohahobg** [comment]
https://discord.com/invite/xVcKDEgd

And if your Pterodactyl does not send emails that seems question for Pterodactyl panel.

**Comment by JockerGamer** [comment]
![image](https://github.com/user-attachments/assets/da002f68-19fa-4781-b6c9-ec7410c0f072)
Finally, since it wasn't sending the email, I created an email to be sent automatically instructing the users. Thank you, wohahobg, for the support.
