### ISSUE TITLE
Error when creating servers with modules

### ISSUE THREAD

**Issue by kcorr** [wohahobg/pterosync#29]
I'm a bit confused on this error when I create new servers. However it still creates the game server. Could you help me out, please?

Action:
patch - https://panel.corr.cloud/api/application/servers/101/build?include=allocations

Request:
{"memory":0,"swap":0,"io":500,"cpu":0,"disk":0,"oom_disabled":true,"feature_limits":{"databases":0,"allocations":1,"backups":1},"allocation":1968,"remove_allocations":[1968],"add_allocations":[1968]}

Response:
Array
(
    [errors] => Array
        (
            [0] => Array
                (
                    [code] => DisplayException
                    [status] => 400
                    [detail] => You are attempting to delete the default allocation for this server but there is no fallback allocation to use.
                )

        )

    [status_code] => 400
)

**Comment by wohahobg** [comment]
Hmm that's so wired.

Neve seen such as thing. Can you share me more pictures form the module log,

Also does your node have enough ports created?

**Comment by kcorr** [comment]
It still creates the server just fine, but throws this error, ND it allocates the correct ports.
I will send screenshots soon.

**Comment by kcorr** [comment]
Let me know what else you'd like to see!

![image](https://github.com/user-attachments/assets/49cc54a7-62d4-44e8-a6f5-a15bd601fe30)

**Comment by wohahobg** [comment]
Is this the main branch, what version is the module ?

**Comment by kcorr** [comment]
I am running the latest version.

**Comment by kcorr** [comment]
Here's the module settings of one throwing the same error.

![image](https://github.com/user-attachments/assets/afd898d6-1b77-4326-b3cf-f947faeea4a9)

**Comment by wohahobg** [comment]
Yes, somebody also reported that on our Discord server. I will try to fix it now. I will let you know when is ready.

**Comment by kcorr** [comment]
Roger! Thank you!

**Comment by MennoGamed** [comment]
I happen to have the same issue. Keep me updated if there’s a fix. Downgrading to the previous version resolves the problem, which indicates that it’s only present in the latest version.

**Comment by wohahobg** [comment]
I forgot to close it. It's fixed in main branch and tested by @kcorr so please download the main branch

I will release an update tomorrow.

**Comment by wohahobg** [comment]
fixed in commit 12b5cddd
