### ISSUE TITLE
The module applies the variable too late

### ISSUE THREAD

**Issue by Fastmancz** [wohahobg/pterosync#37]
I'm running the Unreal Tournament 99 (UT99) game server on Pterodactyl. This game series is known for having a Server Port Offset of +1 for the base SERVER_PORT. The game also allows you to run a Web panel on a specific port.

In Pterodactyl, I have set a WEB_PORT variable for UT99 Egg that the user cannot see. By default, it is set to 999.

Configuration in WHMCS in Module Settings.
```
Port Rangers
{
"SERVER_PORT": "3100-3200",
"WEB_PORT": "3300-3400"
}
```

```
Default Variables
{
"WEB_PORT": "WEB_PORT"
}
```

In the install script, when creating the game server, I have the variable **WEBPANEL_PORT=$WEB_PORT** in the Pterodactyl
After installing the game server, I have **WEB_PORT** output. I tried putting the value **"WEB_PORT": "333"** in Default Variables and this value **333** was reflected in the output, so is working properly. In my opinion, the port that defines the module does not get transferred fast enough before the install script runs.

Module log
```
patch - https://xxx/api/application/servers/69/build?include=allocations
....
[SERVER_MOD] => Botpack.DeathMatchPlus
[SERVER_CONFIG] => UnrealTournament.ini
[SERVER_LOG] => server.log
[SERVER_CUSTOM] => 
[WEB_PORT] => WEB_PORT //The problem is that the variable is not transferred in time and cannot be processed by the installation script (it literally takes the WEB_PORT value).
[STARTUP] => ./System64/ucc-bin server 
....
```
```
found ports
Array
(
    [SERVER_PORT_OFFSET] => Array
        (
            [port] => 3139
            [assigned] => 
            [id] => 140
            [ip] => myip
        )

    [WEB_PORT] => Array
        (
            [port] => 3301
            [assigned] => 
            [id] => 302
            [ip] => myip
        )

)
```
```
post - https://xxx/api/application/servers?include=allocations
...
[SERVER_CONFIG] => UnrealTournament.ini
[SERVER_LOG] => server.log
[SERVER_CUSTOM] => 
[WEB_PORT] => WEB_PORT //The problem is that the variable is not transferred in time and cannot be processed by the installation script (it literally takes the WEB_PORT value).
[STARTUP] => ./System64/ucc-bin server 
...
```
```
patch - https://xxx/api/application/servers/69/startup
[SERVER_MOD] => Botpack.DeathMatchPlus
[SERVER_CONFIG] => UnrealTournament.ini
[SERVER_LOG] => server.log
[SERVER_CUSTOM] => 
[WEB_PORT] => 3301 //Here the variable has already been applied, but too late.
```

**Comment by wohahobg** [comment]
You don't have to do

Default Variables
{
"WEB_PORT": "WEB_PORT"
}

Since default variable will overwrite the values. In the wiki there is examples how it work.

Just leave your ports range and empty default variables .

**Comment by Fastmancz** [comment]
I am attaching pictures for better visualization and understanding. What you describe also works.
![Snímek obrazovky 2024-08-28 083943](https://github.com/user-attachments/assets/7740d96f-d623-4d6b-9a91-cec73ddced0b)
![Snímek obrazovky 2024-08-28 084011](https://github.com/user-attachments/assets/6528de2d-d82f-4bd5-9e1c-5ffd668f002d)
After installing the server, it actually assigned the port to the WEB_PORT variable.
![Snímek obrazovky 2024-08-28 084054](https://github.com/user-attachments/assets/1b242ab2-03fa-4956-b7e0-9c05dd4c3630)
But as I said, the install script that is executed when installing the game server fails to process this variable in time. This is the output of a single file that is saved to the game server after a successful installation of the game server.
![Snímek obrazovky 2024-08-28 084224](https://github.com/user-attachments/assets/1abe781d-40ae-4196-b598-8bbe5a4b88c5)

Here is a short preview of the installation script:
![Snímek obrazovky 2024-08-28 084750](https://github.com/user-attachments/assets/6d9b1097-f8ab-4688-a7dd-b54ab17be0e0)

**Comment by wohahobg** [comment]
So the WEB_PORT must be +1 ?

**Comment by Fastmancz** [comment]
The web port can be any. However, originally I had something like `WEBPANEL_PORT=$((SERVER_PORT + 2))` in the install script ; so the base port would be for example 2700, Query port thanks to SERVER_PORT_OFFSET would be 2701 and WEBPANEL would have port 2702.

But I think your module does not support, for example, SERVER_PORT_OFFSET1 or SERVER_PORT_OFFSET+1 (that would add another port on top of SERVER_PORT_OFFSET)

**Comment by wohahobg** [comment]
Right.

So ports leave as it's then for Default Variables add

{"QUERY_PORT":"SERVER_PORT_OFFSET"}

As mention and shown on the wiki pages

**Comment by Fastmancz** [comment]
I tried it, but it doesn't work. The problem isn't port allocation. The problem is that the module doesn't pass the information fast enough. The installation script starts before it gets information about what ports have been allocated.

**Comment by wohahobg** [comment]
Well the module is passing the information once is available. Is not module issue.

**Comment by wohahobg** [comment]
Try to run the script 30/60 seconds later.

**Comment by Fastmancz** [comment]
This doesn't works too. When I look in MySQL, I can see that the value was indeed allocated immediately. The problem is that the variable is not used when the build is compiled.
![Snímek obrazovky 2024-08-28 093429 (1)](https://github.com/user-attachments/assets/8a24ed37-932b-4c58-be87-413c9bdfc505)

**Comment by Fastmancz** [comment]
It was a real pain, but it works thanks to the API. Below I'm attaching the code how to get data via API into your Egg Install Script. The advantage of this is that you can get whatever values you need. This is basically a preview.
```
### Pterodactyl API ##
# API
API_URL="https://xxxxx.eu/api/application/servers"
API_KEY="ptlc_myapikey"
UUID="$P_SERVER_UUID"

# UUID
SERVER_ID=$(curl -s "$API_URL" \
  -H "Authorization: Bearer $API_KEY" \
  -H "Content-Type: application/json" \
  -H "Accept: Application/vnd.pterodactyl.v1+json" | \
  jq -r --arg uuid "$UUID" '.data[] | select(.attributes.uuid == $uuid) | .attributes.id')

# WEB_PORT
[ -n "$SERVER_ID" ] && WEB_PORT=$(curl -s "$API_URL/$SERVER_ID" \
  -H "Authorization: Bearer $API_KEY" \
  -H "Content-Type: application/json" \
  -H "Accept: Application/vnd.pterodactyl.v1+json" | \
  jq -r '.attributes.container.environment.WEB_PORT')
######################

# Web panel port
WEBPANEL_PORT=$WEB_PORT
```
