### ISSUE TITLE
Control bouton for user is not working

### ISSUE THREAD

**Issue by verticalhost** [wohahobg/pterosync#4]
Hi , 
After couple test i just want to tell you the bouton under user is not working.
We c'ant even start stop from whmcs customer panel.
![image](https://github.com/wohahobg/PteroSync/assets/100486259/dd1726a4-151e-4274-97cd-d4bfcb975259)

**Comment by wohahobg** [comment]
Hi,

Look like you have not setup the Client API KEY. 

In order those buttons to work you have to give Admin Client Api Key.
https://camo.githubusercontent.com/a6d60c6e4b13ba370d119620207df4390db51cd9baad2290cb323e96a3770c4c/68747470733a2f2f63646e2e67616d65636d732e6f72672f706c6174666f726d2f77686d63732d636f6e6e656374696f6e2e706e67

Also please note if the server is not full installed it won't allow you to press the buttons .

**Comment by techisgreat** [comment]
I can confirm i already setup correctly. 
![image](https://github.com/wohahobg/PteroSync/assets/100486259/fc6f2a40-deca-4d93-9c24-096e03ef1a99)

**Comment by verticalhost** [comment]
You have right it was missspell somewhere
