### ISSUE TITLE
An error occurred while communicating with the server. Please try again.

### ISSUE THREAD

**Issue by bencoverts** [wohahobg/pterosync#45]
![image](https://github.com/user-attachments/assets/b1e12895-ed55-425a-a06b-ac58d5a33364)

**Comment by bencoverts** [comment]
My WHMCS Version 8.3.2

**Comment by bencoverts** [comment]
Please Help Me

**Comment by wohahobg** [comment]
This does not says me anything.  

Show with me the module log or enable whmcs errors

**Comment by bencoverts** [comment]
> This does not says me anything.
> 
> Show with me the module log or enable whmcs errors

Where is the Logs Module Located? I didn't find any logs in System Logs

**Comment by wohahobg** [comment]
https://docs.whmcs.com/troubleshooting/logs-in-whmcs/

**Comment by bencoverts** [comment]
> https://docs.whmcs.com/troubleshooting/logs-in-whmcs/

Error: ParseError: syntax error, unexpected '=>' (T_DOUBLE_ARROW) in /home/sundaclo/billing.sundacloud.store/modules/servers/pterosync/pterosync.php:969 Stack trace: #0 /home/sundaclo/billing.sundacloud.store/vendor/whmcs/whmcs-foundation/lib/Module/Server.php(0): WHMCS\Module\AbstractModule->load('pterosync') #1 /home/sundaclo/billing.sundacloud.store/vendor/whmcs/whmcs-foundation/lib/Apps/App/Model.php(0): WHMCS\Module\Server->getAdminActivationForms('pterosync') #2 /home/sundaclo/billing.sundacloud.store/resources/views/admin/apps/modal/info.php(0): WHMCS\Apps\App\Model->getActivationForms() #3 /home/sundaclo/billing.sundacloud.store/vendor/league/plates/src/Template/Template.php(153): include('/home/sundaclo/...') #4 /home/sundaclo/billing.sundacloud.store/vendor/league/plates/src/Engine.php(277): League\Plates\Template\Template->render(NULL) #5 /home/sundaclo/billing.sundacloud.store/includes/functions.php(0): League\Plates\Engine->render('apps/modal/info') #6 /home/sundaclo/billing.sundacloud.store/vendor/whmcs/whmcs-foundation/lib/Admin/Apps/AppsController.php(0): view('admin.apps.moda...', Array) #7 [internal function]: WHMCS\Admin\Apps\AppsController->infoModal(Object(WHMCS\Http\Message\ServerRequest)) #8 /home/sundaclo/billing.sundacloud.store/vendor/middlewares/utils/src/CallableHandler.php(26): call_user_func_array(Array, Array) #9 /home/sundaclo/billing.sundacloud.store/vendor/middlewares/fast-route/src/FastRoute.php(96): Middlewares\Utils\CallableHandler::execute(Array, Array) #10 /home/sundaclo/billing.sundacloud.store/vendor/whmcs/whmcs-foundation/lib/Route/Middleware/HandleProcessor.php(0): Middlewares\FastRoute->process(Object(WHMCS\Http\Message\ServerRequest), Object(Middlewares\Utils\Delegate)) #11 /home/sundaclo/billing.sundacloud.store/vendor/whmcs/whmcs-foundation/lib/Route/Middleware/Strategy/AssumingMiddlewareTrait.php(0): WHMCS\Route\Middleware\HandleProcessor->_process(Object(WHMCS\Http\Message\ServerRequest), Object(Middlewares\Utils\Delegate)) #12 /home/sundaclo/billing.sundacloud.store/vendor/middlewares/utils/src/Dispatcher.php(76): WHMCS\Route\Middleware\HandleProcessor->process(Object(WHMCS\Http\Message\ServerRequest), Object(Middlewares\Utils\Delegate)) #13 [internal function]: Middlewares\Utils\Dispatcher->Middlewares\Utils\{closure}(Object(WHMCS\Http\Message\ServerRequest)) #14 /home/sundaclo/billing.sundacloud.store/vendor/middlewares/utils/src/Delegate.php(31): call_user_func(Object(Closure), Object(WHMCS\Http\Message\ServerRequest)) #15 /home/sundaclo/billing.sundacloud.store/vendor/whmcs/whmcs-foundation/lib/Route/Middleware/Strategy/DelegatingMiddlewareTrait.php(0): Middlewares\Utils\Delegate->process(Object(WHMCS\Http\Message\ServerRequest)) #16 /home/sundaclo/billing.sundacloud.store/vendor/middlewares/utils/src/Dispatcher.php(76): WHMCS\Admin\ApplicationSupport\Route\Middleware\Assent->process(Object(WHMCS\Http\Message\ServerRequest), Object(Middlewares\Utils\Delegate)) #17 [internal function]: Middlewares\Utils\Dispatcher->Middlewares\Utils\{closure}(Object(WHMCS\Http\Message\ServerRequest)) #18 /home/sundaclo/billing.sundacloud.store/vendor/middlewares/utils/src/Delegate.php(31): call_user_func(Object(Closure), Object(WHMCS\Http\Message\ServerRequest)) #19 /home/sundaclo/billing.sundacloud.store/vendor/whmcs/whmcs-foundation/lib/Route/Middleware/Strategy/DelegatingMiddlewareTrait.php(0): Middlewares\Utils\Delegate->process(Object(WHMCS\Http\Message\ServerRequest)) #20 /home/sundaclo/billing.sundacloud.store/vendor/whmcs/whmcs-foundation/lib/Security/Middleware/Authorization.php(0): WHMCS\Security\Middleware\Authorization->delegateProcess(Object(WHMCS\Http\Message\ServerRequest), Object(Middlewares\Utils\Delegate)) #21 /home/sundaclo/billing.sundacloud.store/vendor/whmcs/whmcs-foundation/lib/Route/Middleware/AbstractProxyMiddleware.php(0): WHMCS\Security\Middleware\Authorization->process(Object(WHMCS\Http\Message\ServerRequest), Object(Middlewares\Utils\Delegate)) #22 /home/sundaclo/billing.sundacloud.store/vendor/whmcs/whmcs-foundation/lib/Route/Middleware/Strategy/AssumingMiddlewareTrait.php(0): WHMCS\Route\Middleware\AbstractProxyMiddleware->_process(Object(WHMCS\Http\Message\ServerRequest), Object(Middlewares\Utils\Delegate)) #23 /home/sundaclo/billing.sundacloud.store/vendor/middlewares/utils/src/Dispatcher.php(76): WHMCS\Route\Middleware\AbstractProxyMiddleware->process(Object(WHMCS\Http\Message\ServerRequest), Object(Middlewares\Utils\Delegate)) #24 [internal function]: Middlewares\Utils\Dispatcher->Middlewares\Utils\{closure}(Object(WHMCS\Http\Message\ServerRequest)) #25 /home/sundaclo/billing.sundacloud.store/vendor/middlewares/utils/src/Delegate.php(31): call_user_func(Object(Closure), Object(WHMCS\Http\Message\ServerRequest)) #26 /home/sundaclo/billing.sundacloud.store/vendor/whmcs/whmcs-foundation/lib/Route/Middleware/Strategy/DelegatingMiddlewareTrait.php(0): Middlewares\Utils\Delegate->process(Object(WHMCS\Http\Message\ServerRequest)) #27 /home/sundaclo/billing.sundacloud.store/vendor/whmcs/whmcs-foundation/lib/Route/Middleware/AbstractProxyMiddleware.php(0): WHMCS\Admin\ApplicationSupport\Route\Middleware\Authentication->process(Object(WHMCS\Http\Message\ServerRequest), Object(Middlewares\Utils\Delegate)) #28 /home/sundaclo/billing.sundacloud.store/vendor/whmcs/whmcs-foundation/lib/Route/Middleware/Strategy/AssumingMiddlewareTrait.php(0): WHMCS\Route\Middleware\AbstractProxyMiddleware->_process(Object(WHMCS\Http\Message\ServerRequest), Object(Middlewares\Utils\Delegate)) #29 /home/sundaclo/billing.sundacloud.store/vendor/middlewares/utils/src/Dispatcher.php(76): WHMCS\Route\Middleware\AbstractProxyMiddleware->process(Object(WHMCS\Http\Message\ServerRequest), Object(Middlewares\Utils\Delegate)) #30 [internal function]: Middlewares\Utils\Dispatcher->Middlewares\Utils\{closure}(Object(WHMCS\Http\Message\ServerRequest)) #31 /home/sundaclo/billing.sundacloud.store/vendor/middlewares/utils/src/Delegate.php(31): call_user_func(Object(Closure), Object(WHMCS\Http\Message\ServerRequest)) #32 /home/sundaclo/billing.sundacloud.store/vendor/whmcs/whmcs-foundation/lib/Route/Middleware/Strategy/DelegatingMiddlewareTrait.php(0): Middlewares\Utils\Delegate->process(Object(WHMCS\Http\Message\ServerRequest)) #33 /home/sundaclo/billing.sundacloud.store/vendor/middlewares/utils/src/Dispatcher.php(76): WHMCS\Admin\ApplicationSupport\Route\Middleware\DirectoryValidation->process(Object(WHMCS\Http\Message\ServerRequest), Object(Middlewares\Utils\Delegate)) #34 [internal function]: Middlewares\Utils\Dispatcher->Middlewares\Utils\{closure}(Object(WHMCS\Http\Message\ServerRequest)) #35 /home/sundaclo/billing.sundacloud.store/vendor/middlewares/utils/src/Delegate.php(31): call_user_func(Object(Closure), Object(WHMCS\Http\Message\ServerRequest)) #36 /home/sundaclo/billing.sundacloud.store/vendor/whmcs/whmcs-foundation/lib/Route/Middleware/BackendPsr7Response.php(0): Middlewares\Utils\Delegate->process(Object(WHMCS\Http\Message\ServerRequest)) #37 /home/sundaclo/billing.sundacloud.store/vendor/whmcs/whmcs-foundation/lib/Route/Middleware/BackendPsr7Response.php(0): WHMCS\Route\Middleware\BackendPsr7Response->_process(Object(WHMCS\Http\Message\ServerRequest), Object(Middlewares\Utils\Delegate)) #38 /home/sundaclo/billing.sundacloud.store/vendor/middlewares/utils/src/Dispatcher.php(76): WHMCS\Route\Middleware\BackendPsr7Response->process(Object(WHMCS\Http\Message\ServerRequest), Object(Middlewares\Utils\Delegate)) #39 [internal function]: Middlewares\Utils\Dispatcher->Middlewares\Utils\{closure}(Object(WHMCS\Http\Message\ServerRequest)) #40 /home/sundaclo/billing.sundacloud.store/vendor/middlewares/utils/src/Delegate.php(31): call_user_func(Object(Closure), Object(WHMCS\Http\Message\ServerRequest)) #41 /home/sundaclo/billing.sundacloud.store/vendor/middlewares/utils/src/Dispatcher.php(56): Middlewares\Utils\Delegate->process(Object(WHMCS\Http\Message\ServerRequest)) #42 /home/sundaclo/billing.sundacloud.store/vendor/whmcs/whmcs-foundation/lib/Route/Middleware/BackendDispatch.php(0): Middlewares\Utils\Dispatcher->dispatch(Object(WHMCS\Http\Message\ServerRequest)) #43 /home/sundaclo/billing.sundacloud.store/vendor/whmcs/whmcs-foundation/lib/Route/Middleware/Strategy/AssumingMiddlewareTrait.php(0): WHMCS\Route\Middleware\BackendDispatch->_process(Object(WHMCS\Http\Message\ServerRequest), Object(Middlewares\Utils\Delegate)) #44 /home/sundaclo/billing.sundacloud.store/vendor/middlewares/utils/src/Dispatcher.php(76): WHMCS\Route\Middleware\BackendDispatch->process(Object(WHMCS\Http\Message\ServerRequest), Object(Middlewares\Utils\Delegate)) #45 [internal function]: Middlewares\Utils\Dispatcher->Middlewares\Utils\{closure}(Object(WHMCS\Http\Message\ServerRequest)) #46 /home/sundaclo/billing.sundacloud.store/vendor/middlewares/utils/src/Delegate.php(31): call_user_func(Object(Closure), Object(WHMCS\Http\Message\ServerRequest)) #47 /home/sundaclo/billing.sundacloud.store/vendor/whmcs/whmcs-foundation/lib/Route/Middleware/RoutePathMatch.php(0): Middlewares\Utils\Delegate->process(Object(WHMCS\Http\Message\ServerRequest)) #48 /home/sundaclo/billing.sundacloud.store/vendor/whmcs/whmcs-foundation/lib/Route/Middleware/Strategy/AssumingMiddlewareTrait.php(0): WHMCS\Route\Middleware\RoutePathMatch->_process(Object(WHMCS\Http\Message\ServerRequest), Object(Middlewares\Utils\Delegate)) #49 /home/sundaclo/billing.sundacloud.store/vendor/middlewares/utils/src/Dispatcher.php(76): WHMCS\Route\Middleware\RoutePathMatch->process(Object(WHMCS\Http\Message\ServerRequest), Object(Middlewares\Utils\Delegate)) #50 [internal function]: Middlewares\Utils\Dispatcher->Middlewares\Utils\{closure}(Object(WHMCS\Http\Message\ServerRequest)) #51 /home/sundaclo/billing.sundacloud.store/vendor/middlewares/utils/src/Delegate.php(31): call_user_func(Object(Closure), Object(WHMCS\Http\Message\ServerRequest)) #52 /home/sundaclo/billing.sundacloud.store/vendor/whmcs/whmcs-foundation/lib/Route/Middleware/WhitelistFilter.php(0): Middlewares\Utils\Delegate->process(Object(WHMCS\Http\Message\ServerRequest)) #53 /home/sundaclo/billing.sundacloud.store/vendor/whmcs/whmcs-foundation/lib/Route/Middleware/Strategy/DelegatingMiddlewareTrait.php(0): WHMCS\Route\Middleware\WhitelistFilter->_process(Object(WHMCS\Http\Message\ServerRequest), Object(Middlewares\Utils\Delegate)) #54 /home/sundaclo/billing.sundacloud.store/vendor/middlewares/utils/src/Dispatcher.php(76): WHMCS\Route\Middleware\WhitelistFilter->process(Object(WHMCS\Http\Message\ServerRequest), Object(Middlewares\Utils\Delegate)) #55 [internal function]: Middlewares\Utils\Dispatcher->Middlewares\Utils\{closure}(Object(WHMCS\Http\Message\ServerRequest)) #56 /home/sundaclo/billing.sundacloud.store/vendor/middlewares/utils/src/Delegate.php(31): call_user_func(Object(Closure), Object(WHMCS\Http\Message\ServerRequest)) #57 /home/sundaclo/billing.sundacloud.store/vendor/whmcs/whmcs-foundation/lib/Route/Middleware/RoutableClientModuleRequest.php(0): Middlewares\Utils\Delegate->process(Object(WHMCS\Http\Message\ServerRequest)) #58 /home/sundaclo/billing.sundacloud.store/vendor/whmcs/whmcs-foundation/lib/Route/Middleware/Strategy/AssumingMiddlewareTrait.php(0): WHMCS\Route\Middleware\RoutableClientModuleRequest->_process(Object(WHMCS\Http\Message\ServerRequest), Object(Middlewares\Utils\Delegate)) #59 /home/sundaclo/billing.sundacloud.store/vendor/middlewares/utils/src/Dispatcher.php(76): WHMCS\Route\Middleware\RoutableClientModuleRequest->process(Object(WHMCS\Http\Message\ServerRequest), Object(Middlewares\Utils\Delegate)) #60 [internal function]: Middlewares\Utils\Dispatcher->Middlewares\Utils\{closure}(Object(WHMCS\Http\Message\ServerRequest)) #61 /home/sundaclo/billing.sundacloud.store/vendor/middlewares/utils/src/Delegate.php(31): call_user_func(Object(Closure), Object(WHMCS\Http\Message\ServerRequest)) #62 /home/sundaclo/billing.sundacloud.store/vendor/whmcs/whmcs-foundation/lib/Route/Middleware/RoutableAdminRequestUri.php(0): Middlewares\Utils\Delegate->process(Object(WHMCS\Http\Message\ServerRequest)) #63 /home/sundaclo/billing.sundacloud.store/vendor/whmcs/whmcs-foundation/lib/Route/Middleware/Strategy/AssumingMiddlewareTrait.php(0): WHMCS\Route\Middleware\RoutableAdminRequestUri->_process(Object(WHMCS\Http\Message\ServerRequest), Object(Middlewares\Utils\Delegate)) #64 /home/sundaclo/billing.sundacloud.store/vendor/middlewares/utils/src/Dispatcher.php(76): WHMCS\Route\Middleware\RoutableAdminRequestUri->process(Object(WHMCS\Http\Message\ServerRequest), Object(Middlewares\Utils\Delegate)) #65 [internal function]: Middlewares\Utils\Dispatcher->Middlewares\Utils\{closure}(Object(WHMCS\Http\Message\ServerRequest)) #66 /home/sundaclo/billing.sundacloud.store/vendor/middlewares/utils/src/Delegate.php(31): call_user_func(Object(Closure), Object(WHMCS\Http\Message\ServerRequest)) #67 /home/sundaclo/billing.sundacloud.store/vendor/whmcs/whmcs-foundation/lib/Route/Middleware/RoutableRequestUri.php(0): Middlewares\Utils\Delegate->process(Object(WHMCS\Http\Message\ServerRequest)) #68 /home/sundaclo/billing.sundacloud.store/vendor/whmcs/whmcs-foundation/lib/Route/Middleware/Strategy/AssumingMiddlewareTrait.php(0): WHMCS\Route\Middleware\RoutableRequestUri->_process(Object(WHMCS\Http\Message\ServerRequest), Object(Middlewares\Utils\Delegate)) #69 /home/sundaclo/billing.sundacloud.store/vendor/middlewares/utils/src/Dispatcher.php(76): WHMCS\Route\Middleware\RoutableRequestUri->process(Object(WHMCS\Http\Message\ServerRequest), Object(Middlewares\Utils\Delegate)) #70 [internal function]: Middlewares\Utils\Dispatcher->Middlewares\Utils\{closure}(Object(WHMCS\Http\Message\ServerRequest)) #71 /home/sundaclo/billing.sundacloud.store/vendor/middlewares/utils/src/Delegate.php(31): call_user_func(Object(Closure), Object(WHMCS\Http\Message\ServerRequest)) #72 /home/sundaclo/billing.sundacloud.store/vendor/whmcs/whmcs-foundation/lib/Route/Middleware/RoutableRequestQueryUri.php(0): Middlewares\Utils\Delegate->process(Object(WHMCS\Http\Message\ServerRequest)) #73 /home/sundaclo/billing.sundacloud.store/vendor/whmcs/whmcs-foundation/lib/Route/Middleware/Strategy/AssumingMiddlewareTrait.php(0): WHMCS\Route\Middleware\RoutableRequestQueryUri->_process(Object(WHMCS\Http\Message\ServerRequest), Object(Middlewares\Utils\Delegate)) #74 /home/sundaclo/billing.sundacloud.store/vendor/middlewares/utils/src/Dispatcher.php(76): WHMCS\Route\Middleware\RoutableRequestQueryUri->process(Object(WHMCS\Http\Message\ServerRequest), Object(Middlewares\Utils\Delegate)) #75 [internal function]: Middlewares\Utils\Dispatcher->Middlewares\Utils\{closure}(Object(WHMCS\Http\Message\ServerRequest)) #76 /home/sundaclo/billing.sundacloud.store/vendor/middlewares/utils/src/Delegate.php(31): call_user_func(Object(Closure), Object(WHMCS\Http\Message\ServerRequest)) #77 /home/sundaclo/billing.sundacloud.store/vendor/middlewares/utils/src/Dispatcher.php(56): Middlewares\Utils\Delegate->process(Object(WHMCS\Http\Message\ServerRequest)) #78 /home/sundaclo/billing.sundacloud.store/admin/index.php(0): Middlewares\Utils\Dispatcher->dispatch(Object(WHMCS\Http\Message\ServerRequest)) #79 {main}

**Comment by wohahobg** [comment]
That's says you are not using php 8+.

**Comment by bencoverts** [comment]
I use PHP 8.1

**Comment by bencoverts** [comment]
![image](https://github.com/user-attachments/assets/f8912960-d063-4593-9594-9a505921b94e)
this

**Comment by wohahobg** [comment]
The error `Error: ParseError: syntax error, unexpected '=>' (T_DOUBLE_ARROW) in` clearly says you are no using any php 8+.
If you check with php docs you will find out the same thing.

Create a file test.php and put inside
```php
<?php

echo phpinfo(); 

```

**Comment by bencoverts** [comment]
How to Change PHP Version to Version 8+ Without Ioncube Error? Please I really need this

I use PHP version 7.2 but yesterday I changed it to 8.1 and when I tried to change it back to version 8.2 an error occurred and when I tried to go back to version 8.1 it couldn't.

**Comment by bencoverts** [comment]
Is there a Pterosync Version that supports php Version 7.2?

**Comment by bencoverts** [comment]
![image](https://github.com/user-attachments/assets/f919d4ce-9da5-48de-bbe1-03d4d1992673)

**Comment by wohahobg** [comment]
> Is there a Pterosync Version that supports php Version 7.2?

No. It work only with php 8+.

**Comment by wohahobg** [comment]
> How to Change PHP Version to Version 8+ Without Ioncube Error? Please I really need this
> 
> I use PHP version 7.2 but yesterday I changed it to 8.1 and when I tried to change it back to version 8.2 an error occurred and when I tried to go back to version 8.1 it couldn't.

Update your Ioncube. WHMCS Already support 8+ and many hosts are using php 8+ with the right Ioncube.

**Comment by bencoverts** [comment]
I have changed my WHMCS version to Version 8.9 and it works, thank you for helping me Good Luck
