### ISSUE TITLE
QUERY_PORT _ Small issue maybe you can help

### ISSUE THREAD

**Issue by verticalhost** [wohahobg/pterosync#5]
Hi , 
I am sorry for those issue i open today. 
I solved almost everythings now from my end. 
I have question about this variable i have to enter : QUERY_PORT 
[Pterodactyl Eggs - Enshrouded](https://github.com/gOOvER/own-pterodactyl-eggs/blob/main/steamcmd/enshrouded/egg-enshrouded-proton.json)

This Eggs need Query_Port but it seems with my configuration 
![image](https://github.com/wohahobg/PteroSync/assets/100486259/aaba0743-1881-469e-8d3b-7b614ea418bc)
It's not solving the issue of creating auto-server. 

After server creation it gave me error of not node available be cause it not giving any Query-Port to let's it create or auto-assing it.
Can you help me solving this

When i put same settings on previous screenshot it gave me this error 

![image](https://github.com/wohahobg/PteroSync/assets/100486259/81e9a09f-bb24-45fb-8f36-79584453f344)

And this is on module logs put i have enter previously some range for Query port

[detail] => The [SERVER] Steam Query Port variable must be a number.

![image](https://github.com/wohahobg/PteroSync/assets/100486259/a3f6f51b-9196-4b3c-89c9-bcd036984ad1)

I would like to say some one from Enshrouded told me i have to doo this 

![image](https://github.com/wohahobg/PteroSync/assets/100486259/9391ee85-1b43-4b6c-891c-83e1a469953b)

**Comment by wohahobg** [comment]
Hi,

In order to make gameport+1 you need to remove the query_port from the ports range.

Example:
Ports : ``{"SERVER_PORT": "22003-22033"}``
Default Variables: ``{"QUERY_PORT": "SERVER_PORT_OFFSET"}``
Port offset: `1`
![image](https://github.com/wohahobg/PteroSync/assets/21145247/087f92e4-d1ea-4f45-9af3-929ccbccc5b9)

Also i do recommend to edit the variables  for that egg in this way:
![image](https://github.com/wohahobg/PteroSync/assets/21145247/4ec8326c-e119-4a4c-a05c-dca01c5d2b44)

**Comment by techisgreat** [comment]
Thanks for this information. 
I am now facing this issue 

Array
(
    [errors] => Array
        (
            [0] => Array
                (
                    [code] => ValidationException
                    [status] => 422
                    [detail] => The [SERVER] Steam Query Port variable field is required.
                    [meta] => Array
                        (
                            [source_field] => environment.QUERY_PORT
                            [rule] => required
                        )

                )

        )

    [status_code] => 422
)


It looks it's not giving information

**Comment by cnluminous** [comment]
I followed the settings in the picture, but the queryport is still empty. How should I set it? No matter how I set SERVER_ PORT_ OFF SET is still empty

**Comment by cnluminous** [comment]
![image](https://github.com/wohahobg/PteroSync/assets/47070284/92fe6d12-e6ff-4602-b6a0-9730c285070e)
This is my setup, I can't find the root cause of the problem

![image](https://github.com/wohahobg/PteroSync/assets/47070284/fa716427-da05-44f8-949c-488c0977cd19)
whmcs report
