### ISSUE TITLE
Cron jobs making error from pterosync 

### ISSUE THREAD

**Issue by verticalhost** [wohahobg/pterosync#6]
Hi , Just to let's you know. 
Day cron is making error from your PteroSync. 
Doo you have any clue. 

` Tenant Usage Metrics
ParseError: syntax error, unexpected '=>' (T_DOUBLE_ARROW) in /home/sites/17a/5/578f328353/public_html/modules/servers/pterosync/pterosync.php:880

#0 /home/sites/17a/5/578f328353/public_html/vendor/whmcs/whmcs-foundation/lib/Product/Server.php(0): WHMCS\Module\AbstractModule->load('pterosync')
#1 /home/sites/17a/5/578f328353/public_html/vendor/whmcs/whmcs-foundation/lib/Product/Server.php(0): WHMCS\Product\Server->getModuleInterface()
#2 /home/sites/17a/5/578f328353/public_html/vendor/whmcs/whmcs-foundation/lib/Cron/Task/TenantUsageMetrics.php(0): WHMCS\Product\Server->getMetricProvider()
#3 /home/sites/17a/5/578f328353/public_html/vendor/whmcs/whmcs-foundation/lib/Scheduling/Task/AbstractTask.php(0): WHMCS\Cron\Task\TenantUsageMetrics->__invoke()
#4 /home/sites/17a/5/578f328353/public_html/vendor/whmcs/whmcs-foundation/lib/Scheduling/Task/AbstractTask.php(0): WHMCS\Scheduling\Task\AbstractTask->execute()
#5 /home/sites/17a/5/578f328353/public_html/vendor/whmcs/whmcs-foundation/lib/Cron/Console/Command/AbstractCronCommand.php(0): WHMCS\Scheduling\Task\AbstractTask->run()
#6 /home/sites/17a/5/578f328353/public_html/vendor/whmcs/whmcs-foundation/lib/Cron/Console/Command/AbstractCronCommand.php(0): WHMCS\Cron\Console\Command\AbstractCronCommand->executeCollection(Object(WHMCS\Scheduling\Task\Collection))
#7 /home/sites/17a/5/578f328353/public_html/vendor/symfony/console/Command/Command.php(298): WHMCS\Cron\Console\Command\AbstractCronCommand->execute(Object(WHMCS\Cron\Console\Input\CliInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /home/sites/17a/5/578f328353/public_html/vendor/symfony/console/Application.php(1028): Symfony\Component\Console\Command\Command->run(Object(WHMCS\Cron\Console\Input\CliInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /home/sites/17a/5/578f328353/public_html/vendor/symfony/console/Application.php(299): Symfony\Component\Console\Application->doRunCommand(Object(WHMCS\Cron\Console\Command\AllCommand), Object(WHMCS\Cron\Console\Input\CliInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /home/sites/17a/5/578f328353/public_html/vendor/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun(Object(WHMCS\Cron\Console\Input\CliInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /home/sites/17a/5/578f328353/public_html/crons/cron.php(0): Symfony\Component\Console\Application->run(Object(WHMCS\Cron\Console\Input\CliInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 {main}`

**Comment by wohahobg** [comment]
Hi ,

Look like our php version does not match the module requirements. Please make sure you are using php 8.0+.

**Comment by verticalhost** [comment]
Thanks that solved issue 👯
