### ISSUE TITLE
The Port format is invalid.

### ISSUE THREAD

**Issue by BGDrew** [wohahobg/pterosync#8]
I'm getting the Error The Port format is invalid. iv followed the installation steps and iv also contacted WHMCS they have stated its and issue this end not theirs end,
can you help with this?

thanks

![error](https://github.com/wohahobg/PteroSync/assets/162998762/43f6e774-de55-46f4-8e97-8a7e77824d13)

**Comment by wohahobg** [comment]
Hi,

Please remove https:// from the hostname , leave it only the hostname. 

Example: panel.example.com

**Comment by BGDrew** [comment]
Thank you so much i also had api keys the wrong way round lol

**Comment by BGDrew** [comment]
Solved
