### ISSUE TITLE
Failed to create server because ports is not in valid json format.

### ISSUE THREAD

**Issue by BGDrew** [wohahobg/pterosync#9]
Sorry i have another one when testing to see if it will create a server im getting Error Failed to create server because ports is not in valid json format.
![error](https://github.com/wohahobg/PteroSync/assets/162998762/0ed1e149-6ced-4800-8209-c2ef08c9ca38)

**Comment by wohahobg** [comment]
Hi,

Please checkout the module wiki https://github.com/wohahobg/PteroSync/wiki/Ports-Ranges and validate your json using https://jsonlint.com 


Example of Ports Range: 

```
{"SERVER_PORT": "7777-7780", "QUERY_PORT": "27015-27019", "RCON_PORT": "27020-27030","EXTRA_ALLOCATION": "27019-27030:2"}
```

or

```
{"SERVER_PORT": "3000-4000,4000-5000"}
```
